//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManager.Web.Resources.FlightManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Startup_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Startup_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlightManager.Web.Resources.FlightManager.Startup.en", typeof(Startup_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Type.
        /// </summary>
        internal static string AircraftType {
            get {
                return ResourceManager.GetString("AircraftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Flight.
        /// </summary>
        internal static string ButtonAddFlight {
            get {
                return ResourceManager.GetString("ButtonAddFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Flight.
        /// </summary>
        internal static string ButtonUpdateFlight {
            get {
                return ResourceManager.GetString("ButtonUpdateFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Airport.
        /// </summary>
        internal static string DepartureAirport {
            get {
                return ResourceManager.GetString("DepartureAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Airport.
        /// </summary>
        internal static string DestinationAirport {
            get {
                return ResourceManager.GetString("DestinationAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string DropDownSelect {
            get {
                return ResourceManager.GetString("DropDownSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DestiFlightnation.
        /// </summary>
        internal static string Flight {
            get {
                return ResourceManager.GetString("Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Information.
        /// </summary>
        internal static string FlightInformation {
            get {
                return ResourceManager.GetString("FlightInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flights.
        /// </summary>
        internal static string Flights {
            get {
                return ResourceManager.GetString("Flights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Consumption.
        /// </summary>
        internal static string FuelConsumption {
            get {
                return ResourceManager.GetString("FuelConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Type.
        /// </summary>
        internal static string HeaderAircraftType {
            get {
                return ResourceManager.GetString("HeaderAircraftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        internal static string HeaderDeparture {
            get {
                return ResourceManager.GetString("HeaderDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string HeaderDestination {
            get {
                return ResourceManager.GetString("HeaderDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance (Km).
        /// </summary>
        internal static string HeaderDistanceKm {
            get {
                return ResourceManager.GetString("HeaderDistanceKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel (L).
        /// </summary>
        internal static string HeaderFuelL {
            get {
                return ResourceManager.GetString("HeaderFuelL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Flights Found.
        /// </summary>
        internal static string MessageNoFlightsFound {
            get {
                return ResourceManager.GetString("MessageNoFlightsFound", resourceCulture);
            }
        }
    }
}
